<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Display</title>
</head>
<body>
	<h1 style="text-align: center; color: Blue;">Displaying WebSeries Info!!!</h1>
	<pre>
	<h2 style=" color: black;">
	
	1.SeriesName:<%=request.getParameter("seriesName")%>	
	2.SeriesProducer:<%=request.getParameter("seriesProducer")%>	
	3.SeriesDirector:<%=request.getParameter("seriesDirector")%>
	4.SeriesLightMen:<%=request.getParameter("seriesLightMen")%>
	5.SeriesChoreographer:<%=request.getParameter("seriesChoreographer")%>
	6.SeriesStylish:<%=request.getParameter("seriesStylish")%>
	7.SeriesNo:<%=request.getParameter("seriesNo")%>
	8.SeriesIsAvaliable:<%=request.getParameter("netflix")%>
	                    <%=request.getParameter("jiocinema")%>
	9.SeriesViewer:<%=request.getParameter("seriesViewer")%>
	10.SeriesHero:<%=request.getParameter("seriesHero")%>
	11.SeriesHeroin:<%=request.getParameter("seriesHeroin")%>
	12.SeriesCast:<%=request.getParameter("seriesCast")%>
	13.Budget:<%=request.getParameter("budget")%>
	14.AllRoundBudget:<%=request.getParameter("allBudget")%>
	15.TelecastDay:<%=request.getParameter("telecastDay")%>
	16.NoOfChannel:<%=request.getParameter("channel")%>
	17.MusicDirector:<%=request.getParameter("musicDirector")%>
	18.Music:<%=request.getParameter("music")%>
	19.LyricsComposer:<%=request.getParameter("lyricsComposer")%>
	20.LyricsLanguage:<%=request.getParameter("lyricsLanguage")%>
	21.SeriesLanguage:<%=request.getParameter("seriesLanguage")%>
	22.SeriesWriter:<%=request.getParameter("seriesWriter")%>
	23.SeriesTrailer:<%=request.getParameter("seriesTrailer")%>
	24.SeriesInformation:<%=request.getParameter("seriesInformation")%>
	25.NoOfInstruments:<%=request.getParameter("noOfInstruments")%>
	26.Location:<%=request.getParameter("location")%>
	27.Area:<%=request.getParameter("area")%>
	28.Country:<%=request.getParameter("country")%>
	29.State:<%=request.getParameter("state")%>
	30.HeroinCaste:<%=request.getParameter("heroinCaste")%>
	31.HeroCaste:<%=request.getParameter("heroCaste")%>
	32.HeroCountry:<%=request.getParameter("heroCountry")%>
	33.HeroinCountry:<%=request.getParameter("heroinCountry")%>
	34.HeroDebut:<%=request.getParameter("heroDebut")%>
	35.HeroinDebut:<%=request.getParameter("heroinDebut")%>
	36.PresentInReligion:<%=request.getParameter("presentInReligion")%>
	37.MaleSinger:<%=request.getParameter("maleSinger")%>
	38.FemaleSinger:<%=request.getParameter("femaleSinger")%>
	39.SeriesChannel:<%=request.getParameter("seriesChannel")%>
	40.DislikedSeries:<%=request.getParameter("dislikedSeries")%>
	41.WatchedSeries:<%=request.getParameter("watched")%>
	42.Flop:<%=request.getParameter("flop")%>
	43.TotalCrewMember:<%=request.getParameter("totalCrewMember")%>
	44.FemaleCrew:<%=request.getParameter("femaleCrew")%>
	45.MaleCrew:<%=request.getParameter("maleCrew")%>
	46.AdultCrew:<%=request.getParameter("adultCrew")%>
	47.OlderCrew:<%=request.getParameter("olderCrew")%>
	48.VillianName:<%=request.getParameter("villianName")%>
	49.StuntMember:<%=request.getParameter("stuntMember")%>
	50.NoOfUsedProp:<%=request.getParameter("noOfUsedProp")%>
	51.SeriesName:<%=request.getParameter("seriesName")%>
	52.BudgetFriendly:<%=request.getParameter("budgetFriendly")%>
	53.Age:<%=request.getParameter("age")%>
	54.AgeLimit:<%=request.getParameter("ageLimit")%>
	55.Hd:<%=request.getParameter("hd")%>
	56.SeriesAvaliable:<%=request.getParameter("seriesAvaliable")%>
	57.SeriesCode:<%=request.getParameter("seriesCode")%>
	58.SeriesPaid:<%=request.getParameter("seriesPaid")%>
	59.SeriesUniqueNo:<%=request.getParameter("seriesUniqueNo")%>
	60.LikedSong:<%=request.getParameter("likedSong")%>
	61.UnlikedSong:<%=request.getParameter("unlikedSong")%>
	62.Biopic:<%=request.getParameter("biopic")%>
	63.UnderRated:<%=request.getParameter("underrated")%>
	64.Quality:<%=request.getParameter("quality")%>
	65.ReleasedOn:<%=request.getParameter("releasedOn")%>
	
	</h2>
	</pre>
</body>
</html>